spring:
  application:
    name: ribbon-consumer-service
server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:1111/eureka
    instance:
      lease-renewal-interval-in-seconds: 10
