spring:
  application:
      name: eureka-server
server:
  port: 1111

eureka:
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://peer2:1112/eureka
    instance:
        lease-renewal-interval-in-seconds: 10