spring:
  application:
    name: eureka-server
server:
  port: 1112

eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:1111/eureka
#    instance:
#      lease-renewal-interval-in-seconds: 10